// js/packages/tur-solidjs/src/components.ts
import type { JSX } from "solid-js";
import type { Style } from "./style";
import type { Color } from "./generated/Color";
import type { CrossAxisAlignment } from "./generated/CrossAxisAlignment";
import type { MainAxisAlignment } from "./generated/MainAxisAlignment";
import type { StackFit } from "./generated/StackFit";

interface BaseProps {
  style?: Style;
  children?: JSX.Element;
}

export interface ColumnProps extends BaseProps {
  mainAlignment?: MainAxisAlignment;
  crossAlignment?: CrossAxisAlignment;
}

export interface RowProps extends BaseProps {
  mainAlignment?: MainAxisAlignment;
  crossAlignment?: CrossAxisAlignment;
}

export interface ExpandedProps extends BaseProps {
  flex?: number;
}

export interface StackProps extends BaseProps {
  fit?: StackFit;
}

export interface PositionedProps extends BaseProps {
  left?: number;
  top?: number;
  right?: number;
  bottom?: number;
}

export interface SizedBoxProps extends BaseProps {
  width?: number;
  height?: number;
}

export interface ContainerProps extends BaseProps {
  padding?: number;
  color?: Color;
}

export interface TextProps extends BaseProps {
  content: string;
  fontSize?: number;
  color?: Color;
}

function widget() {
  return globalThis.tur.widget;
}

function applyChildren(el: number, children: JSX.Element | undefined): void {
  if (children == null || children === false) return;
  if (Array.isArray(children)) {
    for (const child of children) {
      if (child != null && child !== false) {
        widget().appendChild(el, child as number);
      }
    }
  } else {
    widget().appendChild(el, children as number);
  }
}

function setAttr(el: number, key: string, value: string | number | boolean): void {
  widget().setAttribute(el, key, value);
}

export function Column(props: ColumnProps): JSX.Element {
  const el: number = widget().createElement("Column");
  if (props.mainAlignment != null) setAttr(el, "mainAlignment", props.mainAlignment);
  if (props.crossAlignment != null) setAttr(el, "crossAlignment", props.crossAlignment);
  props.style?.apply(el);
  applyChildren(el, props.children);
  return el;
}

export function Row(props: RowProps): JSX.Element {
  const el: number = widget().createElement("Row");
  if (props.mainAlignment != null) setAttr(el, "mainAlignment", props.mainAlignment);
  if (props.crossAlignment != null) setAttr(el, "crossAlignment", props.crossAlignment);
  props.style?.apply(el);
  applyChildren(el, props.children);
  return el;
}

export function Expanded(props: ExpandedProps): JSX.Element {
  const el: number = widget().createElement("Expanded");
  if (props.flex != null) setAttr(el, "flex", props.flex);
  props.style?.apply(el);
  applyChildren(el, props.children);
  return el;
}

export function Stack(props: StackProps): JSX.Element {
  const el: number = widget().createElement("Stack");
  if (props.fit != null) setAttr(el, "fit", props.fit);
  props.style?.apply(el);
  applyChildren(el, props.children);
  return el;
}

export function Positioned(props: PositionedProps): JSX.Element {
  const el: number = widget().createElement("Positioned");
  if (props.left != null) setAttr(el, "left", props.left);
  if (props.top != null) setAttr(el, "top", props.top);
  if (props.right != null) setAttr(el, "right", props.right);
  if (props.bottom != null) setAttr(el, "bottom", props.bottom);
  props.style?.apply(el);
  applyChildren(el, props.children);
  return el;
}

export function SizedBox(props: SizedBoxProps): JSX.Element {
  const el: number = widget().createElement("SizedBox");
  if (props.width != null) setAttr(el, "width", props.width);
  if (props.height != null) setAttr(el, "height", props.height);
  props.style?.apply(el);
  applyChildren(el, props.children);
  return el;
}

export function Container(props: ContainerProps): JSX.Element {
  const el: number = widget().createElement("Container");
  if (props.padding != null) setAttr(el, "padding", props.padding);
  if (props.color != null) setAttr(el, "color", String(props.color));
  props.style?.apply(el);
  applyChildren(el, props.children);
  return el;
}

export function Text(props: TextProps): JSX.Element {
  const el: number = widget().createElement("Text");
  setAttr(el, "content", props.content);
  if (props.fontSize != null) setAttr(el, "fontSize", props.fontSize);
  if (props.color != null) setAttr(el, "color", String(props.color));
  props.style?.apply(el);
  applyChildren(el, props.children);
  return el;
}

// js/packages/tur-react/src/components.tsx
import type {
    BorderPosition,
    FlexFit,
    ResourceHandle,
    StackFit,
    TextEditingController,
    TurKeyEvent,
    TurNodeHandle,
} from "@tur/react-renderer";
import {
    BoxFit,
    type Color,
    CrossAxisAlignment,
    FlexDirection,
    type HitTestBehavior,
    type LinearGradient,
    MainAxisAlignment,
    type MainAxisSize,
} from "@tur/react-renderer";
import type { ReactNode, Ref } from "react";
import React from "react";

interface BaseProps {
    children?: ReactNode;
    queryKey?: string[];
}

export interface ColumnProps extends BaseProps {
    mainAlignment?: MainAxisAlignment;
    crossAlignment?: CrossAxisAlignment;
    mainAxisSize?: MainAxisSize;
}

export interface RowProps extends BaseProps {
    mainAlignment?: MainAxisAlignment;
    crossAlignment?: CrossAxisAlignment;
    mainAxisSize?: MainAxisSize;
}

export interface ExpandedProps extends BaseProps {
    flex?: number;
    fit?: FlexFit;
}

export interface StackProps extends BaseProps {
    fit?: StackFit;
}

export interface PositionedProps extends BaseProps {
    left?: number;
    top?: number;
    right?: number;
    bottom?: number;
}

export interface SizedBoxProps extends BaseProps {
    width?: number;
    height?: number;
}

export interface ContainerProps extends BaseProps {
    width?: number;
    height?: number;
    padding?: number;
    color?: Color | LinearGradient;
    borderColor?: Color;
    borderWidth?: number;
    borderRadius?: number;
    borderPosition?: BorderPosition;
    shadowColor?: Color;
    shadowOffset?: [number, number];
    shadowBlur?: number;
}

export interface PointerInteractProps {
    onClick?: () => void;
    onPointerEnter?: () => void;
    onPointerExit?: () => void;
    behavior?: HitTestBehavior;
    child?: ReactNode;
}

export interface FocusableProps {
    ref?: Ref<TurNodeHandle>;
    onFocus?: () => void;
    onBlur?: () => void;
    onKeyDown?: (e: TurKeyEvent) => boolean | void;
    onKeyUp?: (e: TurKeyEvent) => boolean | void;
    child?: ReactNode;
}

export function Column(props: ColumnProps) {
    const {
        children,
        crossAlignment,
        mainAlignment,
        mainAxisSize,
        queryKey,
        ...rest
    } = props;
    return (
        <tur_flex
            direction={FlexDirection.Vertical}
            crossAlignment={crossAlignment ?? CrossAxisAlignment.Stretch}
            mainAlignment={mainAlignment}
            mainAxisSize={mainAxisSize}
            queryKey={queryKey}
            {...rest}
        >
            {children}
        </tur_flex>
    );
}

export function Row(props: RowProps) {
    const {
        children,
        mainAlignment,
        crossAlignment,
        mainAxisSize,
        queryKey,
        ...rest
    } = props;
    return (
        <tur_flex
            direction={FlexDirection.Horizontal}
            mainAlignment={mainAlignment ?? MainAxisAlignment.Start}
            crossAlignment={crossAlignment ?? CrossAxisAlignment.Stretch}
            mainAxisSize={mainAxisSize}
            queryKey={queryKey}
            {...rest}
        >
            {children}
        </tur_flex>
    );
}

export function Expanded(props: ExpandedProps) {
    return (
        <tur_flex_item
            flex={props.flex}
            fit={props.fit}
            queryKey={props.queryKey}
        >
            {props.children}
        </tur_flex_item>
    );
}

export function Stack(props: StackProps) {
    return (
        <tur_stack fit={props.fit} queryKey={props.queryKey}>
            {props.children}
        </tur_stack>
    );
}

export function Positioned(props: PositionedProps) {
    return (
        <tur_positioned
            left={props.left}
            top={props.top}
            right={props.right}
            bottom={props.bottom}
            queryKey={props.queryKey}
        >
            {props.children}
        </tur_positioned>
    );
}

export function SizedBox(props: SizedBoxProps) {
    return (
        <tur_container
            width={props.width}
            height={props.height}
            queryKey={props.queryKey}
        >
            {props.children}
        </tur_container>
    );
}

export function Container(props: ContainerProps) {
    return (
        <tur_container
            width={props.width}
            height={props.height}
            padding={props.padding}
            color={props.color}
            borderColor={props.borderColor}
            borderWidth={props.borderWidth}
            borderRadius={props.borderRadius}
            borderPosition={props.borderPosition}
            shadowColor={props.shadowColor}
            shadowOffset={props.shadowOffset}
            shadowBlur={props.shadowBlur}
            queryKey={props.queryKey}
        >
            {props.children}
        </tur_container>
    );
}

export function PointerInteract(props: PointerInteractProps) {
    return (
        <tur_pointer_interact
            onClick={props.onClick}
            onPointerEnter={props.onPointerEnter}
            onPointerExit={props.onPointerExit}
            behavior={props.behavior}
        >
            {props.child}
        </tur_pointer_interact>
    );
}

export function Focusable(props: FocusableProps) {
    const { ref, onFocus, onBlur, onKeyDown, onKeyUp, child } = props;
    return (
        <tur_focusable
            ref={ref}
            onFocus={onFocus}
            onBlur={onBlur}
            onKeyDown={onKeyDown}
            onKeyUp={onKeyUp}
        >
            {child}
        </tur_focusable>
    );
}

export interface ParagraphProps extends BaseProps {
    spans?: Array<{
        content: string;
        bold?: boolean;
        italic?: boolean;
        underline?: boolean;
        fontSize?: number;
        color?: Color;
    }>;
    fontSize?: number;
    onSelectionChange?: (anchor: number, end: number) => void;
}

export function Paragraph(props: ParagraphProps) {
    return (
        <tur_paragraph
            spans={props.spans}
            fontSize={props.fontSize}
            onSelectionChange={props.onSelectionChange}
            queryKey={props.queryKey}
        />
    );
}

export interface TextProps extends BaseProps {
    content: string;
    fontSize?: number;
    color?: Color;
}

export function Text(props: TextProps) {
    return (
        <tur_paragraph
            spans={[{ content: props.content, color: props.color }]}
            fontSize={props.fontSize}
            queryKey={props.queryKey}
        />
    );
}

export interface InputProps {
    controller: TextEditingController;
    placeholder?: string;
    fontSize?: number;
    color?: Color;
    placeholderColor?: Color;
    cursorColor?: Color;
    multiline?: boolean;
    width?: number;
    height?: number;
}

export function Input(props: InputProps) {
    const ctrl = props.controller;
    return (
        <tur_container width={props.width} height={props.height}>
            <tur_editable_text
                ref={(el: TurNodeHandle) => ctrl._attach(el)}
                controller={ctrl}
                placeholder={props.placeholder}
                fontSize={props.fontSize ?? 14}
                color={props.color}
                placeholderColor={props.placeholderColor}
                cursorColor={props.cursorColor ?? props.color}
                multiline={props.multiline}
            />
        </tur_container>
    );
}

export interface ImageProps {
    resource: ResourceHandle;
    width?: number;
    height?: number;
    fit?: BoxFit;
    queryKey?: string[];
}

export function Image(props: ImageProps) {
    return (
        <tur_image
            resourceId={props.resource}
            width={props.width}
            height={props.height}
            fit={props.fit ?? BoxFit.Contain}
            queryKey={props.queryKey}
        />
    );
}


export interface SvgProps {
    resource: ResourceHandle;
    width?: number;
    height?: number;
    fit?: BoxFit;
    queryKey?: string[];
}

export function Svg(props: SvgProps) {
    return (
        <tur_svg
            resourceId={props.resource}
            width={props.width}
            height={props.height}
            fit={props.fit ?? BoxFit.Contain}
            queryKey={props.queryKey}
        />
    );
}
