// js/packages/tur-test-cases/solidjs-cases/clickable-text/index.tsx
import { renderRoot } from "@tur/solidjs-renderer";
import { createSignal } from "solid-js";
import { Column, Text, PointerInteract, CrossAxisAlignment } from "@tur/solidjs";

function ClickableText() {
  const [content, setContent] = createSignal("before");

  return (
    <Column crossAlignment={CrossAxisAlignment.Start}>
      <PointerInteract
        onClick={() => setContent("after")}
        child={<Text content={content()} queryKey={["click-text"]} />}
      />
    </Column>
  );
}

renderRoot(ClickableText);

// js/packages/tur-test-cases/react-cases/clickable-text/index.tsx
import { useState } from "react";
import { renderRoot } from "@tur/react-renderer";
import { Column, Text, PointerInteract, CrossAxisAlignment } from "@tur/react";

function ClickableText() {
  const [content, setContent] = useState("before");

  return (
    <Column crossAlignment={CrossAxisAlignment.Start}>
      <PointerInteract
        onClick={() => setContent("after")}
        child={<Text content={content} queryKey={["click-text"]} />}
      />
    </Column>
  );
}

renderRoot(ClickableText);
